### ISSUE TITLE
process: process.memoryUsage did not display any useful data

### ISSUE THREAD

**Issue by lolBig** [Rokid/ShadowNode#104]
always return `{
  "rss": 0,
  "heapTotal": 0,
  "heapUsed": 0,
  "external": 0
}`

**Comment by algebrait** [comment]
Like MemoryUsage implemetation in https://github.com/nodejs/node/blob/master/src/node.cc,
uv_resident_set_memory can get RSS (in fact, read /proc/self/stat)

jmem_heap_get_stats can get heapTotal and heapUsed

**Comment by lolBig** [comment]
that's awesome, i will use those methods to implement it

**Comment by lolBig** [comment]
implemented #114
