### ISSUE TITLE
jerry: record function name in bytecode

### ISSUE THREAD

**Issue by algebrait** [Rokid/ShadowNode#121]

**Comment by algebrait** [comment]
a possible implementation:
Add a field "jmem_cpointer_t name" in ecma_compiled_code_t.
In parser, record function name string by calling ecma_find_or_create_literal_string(), which return what we need.

**Comment by yorkie** [comment]
Thank you @algebrait, does this increase the memory?

**Comment by algebrait** [comment]
see PR
#123 
memory should be tested.

**Comment by algebrait** [comment]
Every bytecode add an ecma_value_t. It's acceptable.
Consider string storage: for top level function, name string is already exist because it's a field of global. for function expression `var var1 = function foo(){}`, foo is not added before this PR.
So real world application memory test is need.

**Comment by algebrait** [comment]
Only pure function supported now. I have no idea for arrow function , getter setting, external function. They are ECMA_VALUE_EMPTY now. Perhaps should use magic string. Any better idea?

**Comment by algebrait** [comment]
merge PR
#123
#136
