### ISSUE TITLE
build: add linters for JavaScript and clang

### ISSUE THREAD

**Issue by yorkie** [Rokid/ShadowNode#125]
We need 2 linters for our codebase:

- [ ] ESLint for JavaScript
- [x] clang linter?

If somebody has better option, please leave your suggestion :)

/cc @Rokid/node-js

**Comment by algebrait** [comment]
https://github.com/Rokid/ShadowNode/blob/master/docs/devs/Coding-Style-Guidelines.md

run
./tools/check_tidy.py

**Comment by yorkie** [comment]
Let's add it in tools/build.py and CI :)

**Comment by yorkie** [comment]
Fixed at #128 by @legendecas :)
