### ISSUE TITLE
http: support chunked transfer-encoding

### ISSUE THREAD

**Issue by legendecas** [Rokid/ShadowNode#133]
By default, http module cannot not automatically derive content-length from input data since `ClientRequest` is a duplex stream, client can continuously write data into stream if the stream is not ended, yet headers have been sent at the beginning of the request. 
Thus the http client in node.js set header `Transfer-Encoding` with `chunked` by default, then encase data with an chunk length at the beginning of each chunk.

**Comment by yorkie** [comment]
This has been fixed at #174.
