### ISSUE TITLE
process: emit uncaughtException

### ISSUE THREAD

**Issue by lolBig** [Rokid/ShadowNode#179]
the process exit directly if an uncaught exception was triggerred, should we emit an  uncaughtExecption in process and not exit the process if there are any event listeners

**Comment by yorkie** [comment]
See https://github.com/Rokid/ShadowNode/blob/master/src/js/iotjs.js#L98-L118, this could be what you expected that.

By the way, if report an issue like this, please leave lines of code for reproducing, just closing this.
