### ISSUE TITLE
process: versions

### ISSUE THREAD

**Issue by legendecas** [Rokid/ShadowNode#213]
Attach modules version information to process as following:

### process.versions

The process.versions property returns an object listing the version strings of Node.js and its dependencies. process.versions.modules indicates the current ABI version, which is increased whenever a C++ API changes. Node.js will refuse to load modules that were compiled against a different module ABI version.

```
console.log(process.versions);
```
Will generate an object similar to:

```
{ http_parser: '2.7.0',
  node: '8.9.0',
  v8: '6.3.292.48-node.6',
  uv: '1.18.0',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '60',
  nghttp2: '1.29.0',
  napi: '2',
  openssl: '1.0.2n',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2016b' }
```

Modules that need to be exported:

- [ ] http_parser
- [ ] node
- [ ] tuv/uv
- [ ] zlib
- [ ] mbedtls
- [ ] jerry-script
- [ ] napi

**Comment by yorkie** [comment]
Let's define which versions that needs to export? For example:

- http_parser
- node
- tuv / uv
- zlib
- napi
- mbedtls

**Comment by legendecas** [comment]
@yorkie Just appended a todo list of modules to be exported.

Is it necessary to export N-API version to runtime since the only usage of N-API is at build time?
