### ISSUE TITLE
buffer: toString consumes CPU large

### ISSUE THREAD

**Issue by yorkie** [Rokid/ShadowNode#22]
When an `Buffer` object is 51208 Bytes, the `buffer.toString()` would consumes over 5s to return, consider provide an async way `buffer.toString(fn)` for this purpose :)

/cc @maxbbn

**Comment by algebrait** [comment]
5s is unbelievable long.
Check if GC happened by adding log in ecma_gc_run?

**Comment by yorkie** [comment]
This problem does not exist by the following:

```js
https.get('https://www.baidu.com', (res) => {
  console.log('got response');
  var str = '';
  res.on('data', (chunk) => str += chunk);
  res.on('end', () => {
    console.log('just got end');
    console.log('quit', str);
  });
});
```

The cost of getting response is at network layer, closing this. Feel free to reopen if occurred again :)
