### ISSUE TITLE
number: Number type convenience methods

### ISSUE THREAD

**Issue by legendecas** [Rokid/ShadowNode#222]
- [ ] `Number.isInteger`
- [ ] `Number.isSafeInteger`
- [ ] `Number.isFinite`
- [ ] `Number.isNaN`

**Comment by ErosZy** [comment]
i try to extend jerryscript, and add `Number.isInteger` method, but i have encountered difficulties.

I learn `jerry-core/ecma/builtin-objects` codes, then i write these code:
```c
/* in lit-magic-strings.inc.h */
LIT_MAGIC_STRING_DEF (LIT_MAGIC_STRING_IS_NAN, "isNaN")
LIT_MAGIC_STRING_DEF (LIT_MAGIC_STRING_IS_INTEGER, "isInteger") // new
```
```c
/* in ecma-builtin-number.inc.h */
/* ECMA-262 v5, 15.7.3.1 */
OBJECT_VALUE (LIT_MAGIC_STRING_PROTOTYPE,
              ECMA_BUILTIN_ID_NUMBER_PROTOTYPE,
              ECMA_PROPERTY_FIXED)

ROUTINE (LIT_MAGIC_STRING_IS_INTEGER, ecma_builtin_number_object_is_integer, 0, 0) // new
```
```c
/* in ecma-builtin-number.c  */
static ecma_value_t
ecma_builtin_number_object_is_integer (ecma_value_t this_arg /**< this argument */){ 
  return ECMA_VALUE_UNDEFINED;
}
```
```c
/* in lit-magic-strings.ini */
LIT_MAGIC_STRING_IS_NAN = "isNaN"
LIT_MAGIC_STRING_IS_INTEGER = isInteger
```
finally, i compile my work, and run bin/jerry and example code,  i got undefined.
```javascript
console.log(Number.isInteger) // undefined
```
But when i replace `LIT_MAGIC_STRING_IS_INTEGER` to `LIT_MAGIC_STRING_IS_NAN`, and run example code, it workes
```javascript
console.log(Number.isNaN) // not undefined
```
I don't know why I got the error. I didn't see the relevant documentation. Thank you.

**Comment by ErosZy** [comment]
> Changes in deps/jerry has to be applied by a force clean. Try `tools/build.py --clean`.

It still not works.

**Comment by ErosZy** [comment]
I clone the pr of impl array routines, and change magic string position in the `ecma-magic-string.inc.h`, it also unreachable and returns undefined.  Have any rules? @lolBig

**Comment by legendecas** [comment]
Though I've tried your code. It works for me.

**Comment by ErosZy** [comment]
But it failed when i put magic string near by `LIT_MAGIC_STRING_IS_FINITE`
```shell
LIT_MAGIC_STRING_DEF (LIT_MAGIC_STRING_IS_FINITE, "isFinite")
+#if !defined (CONFIG_DISABLE_NUMBER_BUILTIN)
+LIT_MAGIC_STRING_DEF (LIT_MAGIC_STRING_IS_INTEGER, "isInteger")
+LIT_MAGIC_STRING_DEF (LIT_MAGIC_STRING_IS_SAFE_INTEGER, "isSafeInteger")
+#endif
LIT_MAGIC_STRING_DEF (LIT_MAGIC_STRING_IS_FROZEN_UL, "isFrozen")
```

It have some rules, so make me confused.

**Comment by legendecas** [comment]
lit-magic-strings.inc.h was generated by `deps/jerry/tools/gen-magic-string.py`.
