### ISSUE TITLE
build: improve ci caches for build speed

### ISSUE THREAD

**Issue by legendecas** [Rokid/ShadowNode#275]
* **Version**: 0.9.0
* **Platform**: all
* **Subsystem**: CI

![image](https://user-images.githubusercontent.com/8500303/43879981-235e5808-9bd9-11e8-9e57-7ee532a593a1.png)

Currently for a commit CI consumes half an hour to run lints and tests. Improvements on caches may be applied to speed up CI stages.

**Comment by legendecas** [comment]
There is a half run time reduced with #280 merged, closing for now.

**Comment by yorkie** [comment]
#280 is really saving our building time, that's good job!
