### ISSUE TITLE
test: mock http server

### ISSUE THREAD

**Issue by legendecas** [Rokid/ShadowNode#285]
* **Version**: 0.9.x
* **Platform**: all
* **Subsystem**: test

Setup a mock http/https server to test ShadowNode http/https client to prevent test failure on network unreachability in CI environments.

Possible related tests:

- test/node/parallel/test-http-abort.js
- test/run_pass/test_tls_connect_and_close.js

**Comment by lolBig** [comment]
Do we need mock an MQTT and a Websocket server to test mqtt and websocket client?

**Comment by legendecas** [comment]
As mentioned in #177, mqtt and websocket shall be mocked and tested in its own repository after migrated to a separated repo.

**Comment by lolBig** [comment]
we use native module like mqtt and websocket to parse the protocol header, but the js part is written by ourself, should we test this part?
