### ISSUE TITLE
module: require.resolve

### ISSUE THREAD

**Issue by legendecas** [Rokid/ShadowNode#287]
* **Version**: 0.9.x
* **Platform**: all
* **Subsystem**: module

`require.resolve` is not supported, implementation shall be added for running N-API test set migrated from nodejs/node.

**Comment by Txiaozhe** [comment]
I will try it, is it means we will support: 
```shell
$ node -e "console.log(require.resolve('./package'))"
/Users/mypath/ShadowNode/package.json
```
?

**Comment by yorkie** [comment]
See https://nodejs.org/dist/latest-v10.x/docs/api/modules.html#modules_require_resolve_request_options.

**Comment by Txiaozhe** [comment]
Yes，I will try！thanks

**Comment by Txiaozhe** [comment]
I have support it, can it be closed? :)

**Comment by legendecas** [comment]
close by #445

**Comment by legendecas** [comment]
> I have support it, can it be closed? :)

Yes, it could be closed.

**Comment by Txiaozhe** [comment]
Sure, thanks:)
