### ISSUE TITLE
jerry: external function `this` is not instance of target

### ISSUE THREAD

**Issue by legendecas** [Rokid/ShadowNode#294]
* **Version**: 0.9.x
* **Platform**: all
* **Subsystem**: jerryscript

Short brief:

While constructing an external function, argument `this` is not instance of the external function.

A detailed example can be found in #295 ([goto](https://github.com/Rokid/ShadowNode/pull/295/files#diff-24c74757a99c1d0a58827b53177ba016R14))

**Comment by legendecas** [comment]
Issue caused by https://github.com/Rokid/ShadowNode/blob/master/deps/jerry/jerry-core/api/jerry.c#L2413, which defines this as an undefined.

**Comment by yorkie** [comment]
This should be fixed at #386.
