### ISSUE TITLE
module: error on requiring 0 size js file

### ISSUE THREAD

**Issue by legendecas** [Rokid/ShadowNode#330]
* **Version**: 0.10.0
* **Platform**: all
* **Subsystem**: module

if requiring a zero sized js source file, an error was raised and shadow node exited with non-zero code.

```
Error: Could not load the source.
    at anonymous (module:265:36)
    at anonymous (module:213:23)
    at anonymous (module:300:26)
```

**Comment by yorkie** [comment]
Assigned to you :)

**Comment by Txiaozhe** [comment]
Yes, I will take a look? Thanks:)

**Comment by Txiaozhe** [comment]
In src/modules/iotjs_module_process.c: line 149
```c
if (source == NULL || size == 0) {
  iotjs_string_destroy(&path);
  return JS_CREATE_ERROR(COMMON, "Could not load the source.");
}
```
It will throw error when the module file is empty, I will move it, is it appropriate？
