### ISSUE TITLE
events: Why do we not limit the number of listener? Just like in node. I suggest to.

### ISSUE THREAD

**Issue by Txiaozhe** [Rokid/ShadowNode#337]
In node:
```javascript
EventEmitter.prototype.setMaxListeners = function setMaxListeners(n) {};

EventEmitter.prototype.getMaxListeners = function getMaxListeners() {};
```
etc.

this limit the listener count for event, I suggest to optimize it!

**Comment by yorkie** [comment]
You should think about if where does this feature optimize on low-end device platform.

**Comment by Txiaozhe** [comment]
Oh，I see😯

**Comment by legendecas** [comment]
Closed due to inactivity. /cc @yorkie

**Comment by Txiaozhe** [comment]
For this feature, next I will improve it. Can I open a new one?

**Comment by legendecas** [comment]
Of course, you are welcome.
