### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by houkk** [Rokid/ShadowNode#387]
* **Version**: v0.10.9
* **Platform**: macOS 10.13.6
* **Subsystem**:
When `npm run build` is executed, the error is as follows:
```
ShadowNode/src/modules/iotjs_module_dbus.c:3:10: fatal error: 'dbus/dbus.h' file not found
#include <dbus/dbus.h>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/libiotjs.dir/src/modules/iotjs_module_dbus.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/libiotjs.dir/all] Error 2
make: *** [all] Error 2

[Failed - 2] make -C /Users/kkhou/Github/ShadowNode/build/x86_64-darwin/debug -j
```

**Comment by lolBig** [comment]
please install dbus first, ShadowNode needs dbus at present
you can use brew to install it and add link directories for linking, just like #377

**Comment by Txiaozhe** [comment]
appoint the include path,
try add this cmd in package.json:
"myrebuild": "./tools/build.py --clean --external-include-dir /usr/local/Cellar/dbus/1.12.10/include/dbus-1.0"

**Comment by yorkie** [comment]
Thank @houkk, please try with @Txiaozhe's suggestion and try again, BTW please use a more explicit title looks like this: "build: report dbus header not found".

**Comment by Txiaozhe** [comment]
Thanks! @yorkie @legendecas

**Comment by ft3020997** [comment]
OS: ubuntu 16.04 
Have a try with "sudo apt-get -y install dbus libdbus-1-dev libdbus-glib-1-2 libdbus-glib-1-dev",
which solve my issue.

**Comment by Txiaozhe** [comment]
It seems that ubuntu has built-in dbus? @ft3020997
