### ISSUE TITLE
jerry: jerry-test failed

### ISSUE THREAD

**Issue by algebrait** [Rokid/ShadowNode#426]
* **Version**: #386 
* **Platform**: All
* **Subsystem**: jerry

test script:
```shell
$./deps/jerry/tools/run-tests.py --jerry-tests
```

**Comment by legendecas** [comment]
https://github.com/jerryscript-project/jerryscript/issues/736
`regression-test-issue-736.js` failed for external function not available to keyword `instanceof` in JrS.
Yet external function has been normalized in ShadowNode in https://github.com/Rokid/ShadowNode/pull/386. The case should be reviewed.

**Comment by legendecas** [comment]
`tests/jerry/object-literal-3.js` should be only enabled on es2015, yet it's been ran on es5 tests.
