### ISSUE TITLE
`console.time` and `console.timeEnd`

### ISSUE THREAD

**Issue by legendecas** [Rokid/ShadowNode#54]
[`console.time(label: string): void`](https://developer.mozilla.org/en-US/docs/Web/API/Console/time) and [`console.timeEnd(label: string): void`](https://developer.mozilla.org/en-US/docs/Web/API/Console/timeEnd) is not supported yet it is expected to be a stable api

**Comment by legendecas** [comment]
Blocked by #55

**Comment by yorkie** [comment]
Good catch!
