### ISSUE TITLE
built-in module: module `process` behaves anomaly

### ISSUE THREAD

**Issue by legendecas** [Rokid/ShadowNode#59]
If change the module `process` definition in `src/modules.json` to
```json
{
      "native_files": ["modules/iotjs_module_process.c"],
      "init": "InitProcess",
      "js_file": "js/process.js"
}
```

and add a file `src/js/process.js` with contents below

```js
module.exports = native;
```

rebuild project and run iotjs with script below

```js
require('process') === process // `false`, expecting `true`
```

**Comment by yorkie** [comment]
@legendecas What's the purpose to add a `process.js` for this module?

**Comment by legendecas** [comment]
@yorkie I expecting some simple delegations could be written in js rather than plain c, and all built-in module shall be loaded into global scope as defined in `modules.json`.
Yet it seems that module `process` has a way that differs from other built-in module's to be loaded into global scope.

**Comment by yorkie** [comment]
Yea, the `process` module acts as a special role both in Node.js and ShadowNode, in Node.js, what you are expecting is the [lib/internal/bootstrap_node.js](https://github.com/nodejs/node/blob/master/lib/internal/bootstrap_node.js), the same script is [src/js/iotjs](https://github.com/Rokid/ShadowNode/blob/master/src/js/iotjs.js).

**Comment by legendecas** [comment]
👍
