### ISSUE TITLE
https.setTimeout would throw an uncaughtException: TypeError: Expected a function.

### ISSUE THREAD

**Issue by lolBig** [Rokid/ShadowNode#79]
rt

**Comment by legendecas** [comment]
`tls.TLSSocket` do not inherit from `net.Socket` while in node.js does inherit from `net.Socket`. So there are batch of features not implemented in `tls.TLSSocket`.

**Comment by yorkie** [comment]
@legendecas could you please change it consistent with node implementation? I did, but failed.

**Comment by legendecas** [comment]
Resolved by #149
