### ISSUE TITLE
util: util.format crashed when execute util.format('port', 1234)

### ISSUE THREAD

**Issue by lolBig** [Rokid/ShadowNode#96]
the reason may be string.charAt out of range when invoke util.format

**Comment by legendecas** [comment]
#ref: https://github.com/jerryscript-project/jerryscript/pull/2261
Related to a bug of accessing direct string in jerry script

**Comment by yorkie** [comment]
@legendecas Good, may I ask you to pull the 2261 into this project?

**Comment by legendecas** [comment]
Closed by #117
